version: '3'
services:
  opencart:
    build: ./
    user: root
    ports:
      - "80:80"
    volumes:
      - ./opencart/upload:/var/www/html
    # depends_on:
    #   - mysql
    command: >
      bash -c "if [ ! -f /var/www/html/install.lock ]; then
                 wait-for-it mysql:3306 -t 60 &&
                 cp config-dist.php config.php
                 cp admin/config-dist.php admin/config.php
                 php /var/www/html/install/cli_install.php install --username admin --password admin --email email@example.com --http_server http://localhost/ --db_driver mysqli --db_hostname mysql --db_username root --db_password opencart --db_database opencart --db_port 3306 --db_prefix oc_;
                 touch /var/www/html/install.lock;
               fi &&
               apache2-foreground"

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    # depends_on:
    #   - mysql
    ports:
      - "8080:8080"

  memcached:
    image: memcached:latest