version: '3.3'
networks:
    will_net:
      external: true
services:
  mysql:
    image: mysql:latest 
    container_name: mysql
    build: ./mysql

    networks:
      - will_net
    environment:
      #密码设置
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_USER=opencart
      - MYSQL_PASSWORD=opencart
      - MYSQL_DATABASE=opencart
      - SET_CONTAINER_TIMEZONE=true
    volumes:
      - /usr/local/mysql/data:/var/lib/mysql
      - /usr/local/mysql/logs:/var/log/mysql
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3306:3306
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
