version: '3.3'
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - /usr/local/redis/data:/data
      - /usr/local/redis/logs:/logs
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    #配置文件启动
    command: redis-server /usr/local/etc/redis/redis.conf
